#!/bin/bash

revert=false
types=(build ci docs feat fix perf refactor style test chore)
min_length=1
max_length=52

# build regexp
regexp="^[.0-9]+$|"
if $revert; then
    regexp="${regexp}^([Rr]evert|[Mm]erge):? )?.*$|^("
fi
for type in "${types[@]}"
do
  regexp="${regexp}$type|"
done
regexp="${regexp%|})(\(.+\))?: "
regexp="${regexp}.{$min_length,$max_length}$"

if [[ ! $(head -n1 "$1") =~ $regexp ]]; then
  echo -e "[Invalid Commit Message]"
  echo -e "------------------------"
  echo -e "Valid types: ${types[*]}\n"
  echo -e "Max length (first line): $max_length"
  echo -e "Min length (first line): $min_length\n"
  echo -e "Regex: $regexp\n"
  echo -e "Actual commit message: \"$(cat "$1")\""
  echo -e "Actual length:   $(wc -c < "$1")"
  exit 1
fi

regexp="(Ref|Refs): ([A-z0-9\-]+/)+[A-z0-9\-]+#[0-9]+$"
COMMIT_MESSAGE="$(cat "$1")"

if [[ ! "${COMMIT_MESSAGE}" =~ $regexp ]]; then
  echo -e "[No issue reference found]"
  echo -e "--------------------------\n"
  echo -e "Issue reference line should:"
  echo -e " - starts on a new line"
  echo -e " - be separated from the commit message body with an empty line"
  echo -e " - be the last line of the commit message\n"
  echo -e "For more information see: https://guidelines.adprojects.ru/development/git-commit/\n\n"
  echo -e "Regex: $regexp\n"
  echo -e "Actual commit message:\n"
  echo -e "${COMMIT_MESSAGE}"
  exit 1
fi
